### ISSUE TITLE
Wishlist: WebP Support [rt.cpan.org #127780]

### ISSUE THREAD

**Issue by tonycoz** [tonycoz/imager#445]
Migrated from [rt.cpan.org#127780](https://rt.cpan.org/Ticket/Display.html?id=127780) (status was 'new')

Requestors:
* dean@fragfest.com.au

From dean@fragfest.com.au on 2018-11-22 02:53:25
:
```
WebP is being pushed by the big G. Can it please be supported?

https://developers.google.com/speed/webp/

apt-get install libwebp-dev

etc

```

**Comment by djzort** [comment]
i think this could have just been closed on RT?

**Comment by tonycoz** [comment]
Yep, closing here

**Comment by tonycoz** [comment]
It was already done:

https://metacpan.org/pod/Imager::File::WEBP

**Comment by tonycoz** [comment]
The next release of Imager will include a list in Imager::Files of image types that have separate support on CPAN.

**Comment by garu** [comment]
Ha! That's really great, thank you :)
