### ISSUE TITLE
add support for HEIC format

### ISSUE THREAD

**Issue by yahermann** [tonycoz/imager#468]
The HEIC format is quickly becoming popular due to iOS, would love to see support. `libheif` exists and appears robust as a dependency.

**Comment by tonycoz** [comment]
This already exists as a separate module on CPAN:

https://metacpan.org/pod/Imager::File::HEIF

**Comment by yahermann** [comment]
Oops, completely missed that. Can I suggest adding some reference to HEIF support here:
https://metacpan.org/dist/Imager/view/lib/Imager/Files.pod
or similar?

In any case THANK YOU for the pointer, and THANK YOU for Imager!
