### ISSUE TITLE
Imager::Transformations pod typo

### ISSUE THREAD

**Issue by ronsavage** [tonycoz/imager#525]
This text:
For example, if the original image is 400 pixels wide by 200 pixels high and xpixels is set to 300, and ypixels is set to 160. When type is 'min' the resulting image is 300 x 150, when type is 'max' the resulting image is 320 x 160.

Contains a 150 instead of a 160.

**Comment by tonycoz** [comment]
Sorry about the delay in getting back to you.

As far as I can tell the explanation is correct.

This describes a call like:
```
my $img = Imager->new(xsize => 400, ysize => 200); # dimensions 2:1
my $new = $img->scale(xpixels => 300, ypixels => 160, type => $type);
```
Unless `$type` is `nonprop` scale tries to make the ratio of the dimensions of the output image match that of the input image.

In this case the requested size is 300 x 160, which doesn't match that ratio 2:1, we could use xpixels and get 300 x 150 or ypixels and get 320 x 160, `min` selects the smaller size, while `max` selects the larger size.

Did I miss something, or does the pod need more or better words to distinguish the two cases?

**Comment by ronsavage** [comment]
Hi Tony

Oops.  Looks like my misunderstanding. Sorry for the line noise.
