### ISSUE TITLE
TIFF: add CI and support for libtiff supplied with RHEL 8

### ISSUE THREAD

**Issue by tonycoz** [tonycoz/imager#527]
via one of the RHEL clones.

**Comment by gwyn17** [comment]
This patch will get Imager to work with libtiff 4.0.6.
[Imager-zxing.pkc-config.pg1.patch.txt](https://github.com/tonycoz/imager/files/14859564/Imager-zxing.pkc-config.pg1.patch.txt)

**Comment by tonycoz** [comment]
Pretty sure that's the wrong patch :)

**Comment by gwyn17** [comment]
[Imager-1.023-libtiff-4.0-pg1.patch.txt](https://github.com/tonycoz/imager/files/14866111/Imager-1.023-libtiff-4.0-pg1.patch.txt)

It was

**Comment by tonycoz** [comment]
fixed in 1.024
